version: '3.8'

services:
  nuxt:
    build: .
    container_name: nuxt
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NUXT_PUBLIC_SITE_URL=${NUXT_PUBLIC_SITE_URL}
      - NITRO_HOST=${NITRO_HOST}
      - NUXT_PUBLIC_DIRECTUS_URL=${NUXT_PUBLIC_DIRECTUS_URL}
    restart: unless-stopped
    networks:
      - directus_network

  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./extensions:/directus/extensions
      - ./uploads:/directus/uploads
    environment:
      SECRET: ${DIRECTUS_SECRET}
      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}
      
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      
      STORAGE_LOCATIONS: "local,minio"
      STORAGE_LOCAL_DRIVER: "local"
      STORAGE_LOCAL_ROOT: "/directus/uploads"
      STORAGE_MINIO_DRIVER: "s3"
      STORAGE_MINIO_KEY: ${STORAGE_MINIO_KEY}
      STORAGE_MINIO_SECRET: ${STORAGE_MINIO_SECRET}
      STORAGE_MINIO_BUCKET: "directus-bucket"
      STORAGE_MINIO_ENDPOINT: "http://minio:9000"
      STORAGE_MINIO_REGION: ""
      
      WEBSOCKETS_ENABLED: "true"
      
      CORS_ENABLED: "true"
      CORS_ORIGIN: "true"
      CORS_METHODS: "GET,POST,PATCH,DELETE,HEAD,OPTIONS"
      CORS_ALLOWED_HEADERS: "Content-Type,Authorization,Cache-Control,X-Requested-With"
      CORS_EXPOSED_HEADERS: "Content-Range"
      CORS_CREDENTIALS: "true"
      PUBLIC_URL: "${NUXT_PUBLIC_DIRECTUS_URL}"
    depends_on:
      - postgres
      - minio
    networks:
      - directus_network

  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - directus_network
    expose:
      - 5432
  backup:
    image: prodrigestivill/postgres-backup-local
    restart: unless-stopped
    volumes:
      - ./backups:/backups
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
    depends_on:
      - postgres
    networks:
      - directus_network

  minio:
    image: minio/minio
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    networks:
      - directus_network
    expose:
      - 9000
      - 9001

volumes:
  postgres_data:
  minio_data:

networks:
  directus_network:
    driver: bridge